//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import javax.swing.*;

public class BuyingPanel extends JPanel {
    private JButton jcomp1;
    private JButton jcomp2;
    private JButton jcomp3;
    private JTextArea jcomp4;
    private JButton jcomp5;
    private JButton jcomp6;
    private JButton jcomp7;
    private JButton jcomp8;
    private JButton jcomp9;
    private JButton jcomp10;
    private JPasswordField jcomp11;
    private JLabel jcomp12;
    private JButton jcomp13;
    private JButton jcomp14;
    private JButton jcomp15;
    private JComboBox jcomp16;

    public BuyingPanel() {
        //construct preComponents
        String[] jcomp16Items = {"Item 1", "Item 2", "Item 3"};

        //construct components
        jcomp1 = new JButton ("1 Peso");
        jcomp2 = new JButton ("5 Peso");
        jcomp3 = new JButton ("10 Peso");
        jcomp4 = new JTextArea (5, 5);
        jcomp5 = new JButton ("20 Peso");
        jcomp6 = new JButton ("50 Peso");
        jcomp7 = new JButton ("100 Peso");
        jcomp8 = new JButton ("200 Peso");
        jcomp9 = new JButton ("500 Peso");
        jcomp10 = new JButton ("1000 Peso");
        jcomp11 = new JPasswordField (5);
        jcomp12 = new JLabel ("Enter item slot:");
        jcomp13 = new JButton ("Enter");
        jcomp14 = new JButton ("Back");
        jcomp15 = new JButton ("Buy");
        jcomp16 = new JComboBox (jcomp16Items);

        //adjust size and set layout
        setPreferredSize (new Dimension (752, 425));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (jcomp4);
        add (jcomp5);
        add (jcomp6);
        add (jcomp7);
        add (jcomp8);
        add (jcomp9);
        add (jcomp10);
        add (jcomp11);
        add (jcomp12);
        add (jcomp13);
        add (jcomp14);
        add (jcomp15);
        add (jcomp16);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (30, 285, 80, 20);
        jcomp2.setBounds (115, 285, 80, 20);
        jcomp3.setBounds (205, 285, 80, 20);
        jcomp4.setBounds (15, 5, 560, 225);
        jcomp5.setBounds (295, 285, 90, 20);
        jcomp6.setBounds (395, 285, 100, 25);
        jcomp7.setBounds (25, 320, 100, 25);
        jcomp8.setBounds (135, 320, 100, 25);
        jcomp9.setBounds (245, 320, 100, 25);
        jcomp10.setBounds (360, 320, 100, 25);
        jcomp11.setBounds (145, 245, 100, 25);
        jcomp12.setBounds (40, 245, 100, 25);
        jcomp13.setBounds (255, 245, 100, 25);
        jcomp14.setBounds (465, 245, 100, 25);
        jcomp15.setBounds (470, 320, 100, 25);
        jcomp16.setBounds (360, 245, 100, 25);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("MyPanel");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new BuyingPanel());
        frame.pack();
        frame.setVisible (true);
    }
}
