//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import javax.swing.*;

public class SVMFrame extends JPanel {
    private JButton onePeso;
    private JButton fivePeso;
    private JButton tenPeso;
    private JTextArea SelledItems;
    private JButton twentyPeso;
    private JButton fiftyPeso;
    private JButton hundredPeso;
    private JButton twoHundredPeso;
    private JButton fiveHundredPeso;
    private JButton thousandPeso;
    private JLabel enterSpecialItemSlot;
    private JButton Back;
    private JButton Confirm;
    private JComboBox itemSlot;
    private JButton Add;
    private JTextArea Selected_Items;

    public SVMFrame() {
        //construct preComponents
        String[] itemSlotItems = {};

        //construct components
        onePeso = new JButton ("1 Peso");
        fivePeso = new JButton ("5 Peso");
        tenPeso = new JButton ("10 Peso");
        SelledItems = new JTextArea (5, 5);
        twentyPeso = new JButton ("20 Peso");
        fiftyPeso = new JButton ("50 Peso");
        hundredPeso = new JButton ("100 Peso");
        twoHundredPeso = new JButton ("200 Peso");
        fiveHundredPeso = new JButton ("500 Peso");
        thousandPeso = new JButton ("1000 Peso");
        enterSpecialItemSlot = new JLabel ("Enter item slot:");
        Back = new JButton ("Back");
        Confirm = new JButton ("Confirm");
        itemSlot = new JComboBox (itemSlotItems);
        Add = new JButton ("Add");
        Selected_Items = new JTextArea (5, 5);

        //adjust size and set layout
        setPreferredSize (new Dimension (582, 359));
        setLayout (null);

        //add components
        add (onePeso);
        add (fivePeso);
        add (tenPeso);
        add (SelledItems);
        add (twentyPeso);
        add (fiftyPeso);
        add (hundredPeso);
        add (twoHundredPeso);
        add (fiveHundredPeso);
        add (thousandPeso);
        add (enterSpecialItemSlot);
        add (Back);
        add (Confirm);
        add (itemSlot);
        add (Add);
        add (Selected_Items);

        //set component bounds (only needed by Absolute Positioning)
        onePeso.setBounds (25, 285, 80, 20);
        fivePeso.setBounds (115, 285, 80, 20);
        tenPeso.setBounds (205, 285, 80, 20);
        SelledItems.setBounds (20, 5, 320, 225);
        twentyPeso.setBounds (295, 285, 90, 20);
        fiftyPeso.setBounds (395, 285, 100, 25);
        hundredPeso.setBounds (25, 320, 100, 25);
        twoHundredPeso.setBounds (135, 320, 100, 25);
        fiveHundredPeso.setBounds (245, 320, 100, 25);
        thousandPeso.setBounds (360, 320, 100, 25);
        enterSpecialItemSlot.setBounds (20, 240, 100, 25);
        Back.setBounds (470, 245, 100, 25);
        Confirm.setBounds (470, 320, 100, 25);
        itemSlot.setBounds (110, 240, 100, 25);
        Add.setBounds (220, 240, 100, 25);
        Selected_Items.setBounds (345, 5, 230, 225);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("MyPanel");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new SVMFrame());
        frame.pack();
        frame.setVisible (true);
    }
}
